load 'En.rb'
load 'Fr.rb'

@_lang = "en"


if @_lang == "en"

	 MENU_PREMIER = En::MENU_PREMIER
	 MENU_DEUXIEME = En::MENU_DEUXIEME
	 MENU_TROISIEME = En::MENU_TROISIEME
	 SELECT_LANGUE_FR = En::SELECT_LANGUE_FR
	 SELECT_LANGUE_EN = En::SELECT_LANGUE_EN
	 SELECT_LANGUE_SP = En::SELECT_LANGUE_SP
	 MENU_PREMIER = En::MENU_PREMIER
	 MENU_PREMIER = En::MENU_PREMIER
	 MENU_PREMIER = En::MENU_PREMIER
	 LIBELLE_PAGE = En::LIBELLE_PAGE

elsif @_lang == "fr"

	 MENU_PREMIER = Fr::MENU_PREMIER
	 MENU_DEUXIEME = Fr::MENU_DEUXIEME
	 MENU_TROISIEME = Fr::MENU_TROISIEME
	 SELECT_LANGUE_FR = Fr::SELECT_LANGUE_FR
	 SELECT_LANGUE_EN = Fr::SELECT_LANGUE_EN
	 SELECT_LANGUE_SP = Fr::SELECT_LANGUE_SP
	 MENU_PREMIER = Fr::MENU_PREMIER
	 MENU_PREMIER = Fr::MENU_PREMIER
	 MENU_PREMIER = Fr::MENU_PREMIER
	 LIBELLE_PAGE = En::LIBELLE_PAGE
end
